# Generated by Django 4.1.4 on 2023-06-11 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("unsplash_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="user", name="id",),
        migrations.AlterField(
            model_name="user",
            name="user_name",
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
