# Generated by Django 4.1.4 on 2023-06-23 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("unsplash_app", "0003_tag_user_profile_image_post"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="about",
            field=models.CharField(max_length=300, null=True),
        ),
    ]
